services:
  db_students_ci-cd:
    image: postgres
    container_name: db_students_ci-cd
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
  
  node_app_students_ci-cd:
    container_name: node_app_students_ci-cd
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db_students_ci-cd

volumes:
  pg: